services:
  caddy:
    image: caddy
    container_name: caddy-convocations
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend

  mongo:
    image: mongo
    container_name: mongo-convocations
    restart: always
    networks:
      - backend
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend-convocations
    restart: always
    networks:
      - backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/convocationsDB
      - JWT_SECRET=^%Fu3CVKsyhG5vQcmFJbGnJLLzYC#zsx#8hYUnMZNQL&M4uvMKRm1N&E74DR

    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-convocations
    restart: always
    networks:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=https://api.convocations.com/api
    ports:
      - "8081:8080"

volumes:
  mongo-data:
  caddy_data:
  caddy_config:


networks:
  backend:
    driver: bridge
