services:

  mongo:
    image: mongo
    container_name: mongo-convocations
    restart: always
    networks:
      - convocations_network
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend-convocations
    restart: always
    networks:
      - convocations_network
    environment:
      - MONGO_URL=mongodb://mongo:27017/convocationsDB
      - JWT_SECRET=^%Fu3CVKsyhG5vQcmFJbGnJLLzYC#zsx#8hYUnMZNQL&M4uvMKRm1N&E74DR
      - NODE_ENV=production

    depends_on:
      - mongo
    ports:
      - "5050:5050"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-convocations
    restart: always
    networks:
      - convocations_network
    environment:
      - REACT_APP_API_BASE_URL=https://api.convocations.com/api
    ports:
      - "8081:8081"

volumes:
  mongo-data:


networks:
  convocations_network:
    external: true
